# Generated by Django 4.1.3 on 2023-03-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=30)),
                (
                    "expiry_date",
                    models.DateField(
                        error_messages={
                            "invalid": 'Please enter in "YYYY-MM-DD" Format!'
                        }
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        error_messages={"invalid": "Please enter numbers!"}
                    ),
                ),
                (
                    "marked_price",
                    models.FloatField(
                        error_messages={"invalid": "Please enter numbers!"}
                    ),
                ),
                (
                    "discount",
                    models.FloatField(
                        error_messages={"invalid": "Please enter numbers!"}
                    ),
                ),
                ("company", models.CharField(max_length=30)),
                ("dealer", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="User_Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_email",
                    models.EmailField(
                        error_messages={
                            "invalid": "Please enter a valid email address!"
                        },
                        max_length=254,
                    ),
                ),
                ("login_password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User_Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "f_name",
                    models.CharField(
                        error_messages={"invalid": "Please enter letters!"},
                        max_length=30,
                    ),
                ),
                (
                    "l_name",
                    models.CharField(
                        error_messages={"invalid": "Please enter letters!"},
                        max_length=30,
                    ),
                ),
                ("address", models.CharField(max_length=30)),
                (
                    "phone",
                    models.BigIntegerField(
                        error_messages={"invalid": "Please enter 10 digits number!"},
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        error_messages={"invalid": "Please enter your gender!"},
                        max_length=7,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "invalid": "Please enter a valid email address!"
                        },
                        max_length=254,
                    ),
                ),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
