# Generated by Django 4.1.3 on 2023-03-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medkit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_registration",
            name="phone",
            field=models.BigIntegerField(
                error_messages={"invalid": "Please enter 10 digits number!"}
            ),
        ),
        migrations.CreateModel(
            name="Sale_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=30)),
                (
                    "quantity",
                    models.IntegerField(
                        error_messages={"invalid": "Please enter numbers!"}
                    ),
                ),
                (
                    "marked_price",
                    models.FloatField(
                        error_messages={"invalid": "Please enter numbers!"}
                    ),
                ),
                (
                    "discount",
                    models.FloatField(
                        error_messages={"invalid": "Please enter numbers!"}
                    ),
                ),
                (
                    "sale_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medkit.information",
                    ),
                ),
            ],
        ),
    ]
