# Generated by Django 4.1.3 on 2023-03-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medkit", "0003_remove_user_registration_address_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User_Login",
        ),
        migrations.DeleteModel(
            name="User_Registration",
        ),
    ]
