# Generated by Django 4.2 on 2023-04-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medkit", "0007_alter_information_description_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
